import { zodResolver } from "@hookform/resolvers/zod";
import { BriefcaseBusiness, FileText, Link2, Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { useNavigate } from "react-router";
import { useAppDispatch, useAppSelector } from "@/app/hooks";
import { useCreateSessionMutation } from "@/entities/session/api/sessionApi";
import { sessionDraftSchema, type SessionDraft } from "@/entities/session/model/types";
import { clearDraft, saveDraft } from "@/features/interview/model/interviewSlice";
import { getApiErrorMessage } from "@/shared/api/baseApi";
import "./NewInterviewPage.css";

type TrainingMode = "candidate" | "interviewer";
type SourceMode = "link" | "manual";
const levels: ReadonlyArray<{ value: SessionDraft["level"]; text: string }> = [{ value: "junior", text: "Junior" }, { value: "middle", text: "Middle" }, { value: "senior", text: "Senior" }];
const formats: ReadonlyArray<{ value: SessionDraft["format"]; title: string; text: string }> = [{ value: "technical", title: "Техническое", text: "Задачи, архитектура и стек" }, { value: "behavioral", title: "Поведенческое", text: "Опыт, коммуникация и мотивация" }, { value: "mixed", title: "Смешанное", text: "Сбалансированный сценарий" }];

export function NewInterviewPage() {
  const dispatch = useAppDispatch(); const draft = useAppSelector((state) => state.interview.draft); const navigate = useNavigate();
  const [trainingMode, setTrainingMode] = useState<TrainingMode>("candidate"); const [sourceMode, setSourceMode] = useState<SourceMode>("manual");
  const [sessionGoal, setSessionGoal] = useState<"quick" | "standard" | "deep">("standard");
  const [interviewerMode, setInterviewerMode] = useState<"soft" | "neutral" | "strict">("neutral");
  const [createSession, createState] = useCreateSessionMutation();
  const form = useForm<SessionDraft>({ defaultValues: draft, resolver: zodResolver(sessionDraftSchema) });
  const values = useWatch({ control: form.control }); const savedDraftRef = useRef(draft);
  useEffect(() => { const next = { ...savedDraftRef.current, ...values }; if (!isSameDraft(savedDraftRef.current, next)) { savedDraftRef.current = next; dispatch(saveDraft(next)); } }, [dispatch, values]);
  async function create(data: SessionDraft) { try { const request = { trainingMode, source: sourceMode === "link" ? { type: "hh_url" as const, url: data.vacancy.trim() } : { type: "text" as const, text: data.vacancy.trim() }, resumeText: data.profile.trim() || undefined, level: data.level, sessionGoal, focus: data.format === "behavioral" ? "behavioral" as const : data.format === "technical" ? "professional" as const : undefined, interviewerMode }; const session = await createSession(request).unwrap(); dispatch(clearDraft()); navigate(`/interview/${session.id}`); } catch (error) { form.setError("root", { message: getApiErrorMessage(error) }); } }
  return <form className="interview-setup" noValidate onSubmit={form.handleSubmit(create)}>
    <section className="setup-shell"><header className="setup-context-head"><div><p className="panel-label">НОВАЯ РЕПЕТИЦИЯ</p><h1>Настройте контекст интервью</h1><p className="setup-description">Добавьте вакансию и профиль — сценарий будет собран под них.</p></div><div aria-label="Режим тренировки" className="training-mode-switch" role="radiogroup"><Choice active={trainingMode === "candidate"} meta="Вы отвечаете" onClick={() => setTrainingMode("candidate")} title="Кандидат"/><Choice active={trainingMode === "interviewer"} meta="Вы проводите" onClick={() => setTrainingMode("interviewer")} title="Интервьюер"/></div></header>
      <div className="context-grid"><article className="context-column"><div className="panel-head"><p className="panel-label">КОНТЕКСТ</p><h2>{trainingMode === "candidate" ? "Вакансия" : "Роль кандидата"}</h2></div><div className="source-tabs" role="tablist"><Tab active={sourceMode === "link"} icon={<Link2/>} onClick={() => setSourceMode("link")} title="По ссылке"/><Tab active={sourceMode === "manual"} icon={<BriefcaseBusiness/>} onClick={() => setSourceMode("manual")} title="Вручную"/></div><label className="setup-field" htmlFor="vacancy"><span>{sourceMode === "link" ? "Ссылка на вакансию" : "Вакансия"}</span>{sourceMode === "link" ? <input id="vacancy" placeholder="https://hh.ru/vacancy/…" {...form.register("vacancy")}/> : <textarea id="vacancy" placeholder="Название позиции, задачи, технологии и ожидания от кандидата" {...form.register("vacancy")}/>}<ErrorText error={form.formState.errors.vacancy?.message}/></label>{sourceMode === "manual" && <p className="field-hint">Можно вставить описание вакансии целиком или кратко перечислить требования.</p>}</article>
        <article className="context-column context-column--candidate"><div className="panel-head"><p className="panel-label">{trainingMode === "candidate" ? "КАНДИДАТ" : "СЦЕНАРИЙ"}</p><h2>{trainingMode === "candidate" ? "Ваш опыт" : "Портрет кандидата"}</h2></div><p className="source-hint">{trainingMode === "candidate" ? "Расскажите об опыте, ключевых навыках и проектах." : "Опишите опыт кандидата, которого будете интервьюировать."}</p><div className="file-placeholder"><FileText/><span><strong>Контекст кандидата</strong><small>Текст резюме или краткое описание</small></span></div><label className="setup-field" htmlFor="profile"><span className="sr-only">Профиль кандидата</span><textarea id="profile" placeholder="Например: 5 лет во фронтенде, React, TypeScript, опыт работы с дизайн-системами…" {...form.register("profile")}/><ErrorText error={form.formState.errors.profile?.message}/></label></article></div></section>
    <section className="settings-panel"><header className="panel-head"><p className="panel-label">ПАРАМЕТРЫ</p><h2>Сценарий интервью</h2></header><div className="parameter-grid"><OptionGroup title="Формат сессии" values={[{ value: "quick", text: "Быстро · 5 вопросов" }, { value: "standard", text: "Стандарт · 10 вопросов" }, { value: "deep", text: "Глубоко · 15 вопросов" }]} value={sessionGoal} onChange={setSessionGoal}/><OptionGroup title="Стиль интервьюера" values={[{ value: "soft", text: "Поддерживающий" }, { value: "neutral", text: "Нейтральный" }, { value: "strict", text: "Строгий" }]} value={interviewerMode} onChange={setInterviewerMode}/><OptionGroup title="Уровень" values={levels} value={values.level ?? "middle"} onChange={(value) => form.setValue("level", value, { shouldDirty: true })}/><OptionGroup title="Формат вопросов" values={formats} value={values.format ?? "technical"} onChange={(value) => form.setValue("format", value, { shouldDirty: true })}/><section className="parameter-group"><h3>Длительность</h3><div className="select-grid"><label>Вопросов<select aria-label="Количество вопросов" {...form.register("questionsCount", { valueAsNumber: true })}><option value={5}>5 вопросов</option><option value={10}>10 вопросов</option><option value={15}>15 вопросов</option><option value={20}>20 вопросов</option></select></label><label>Время<select aria-label="Длительность, минут" {...form.register("durationMinutes", { valueAsNumber: true })}><option value={15}>15 минут</option><option value={30}>30 минут</option><option value={45}>45 минут</option><option value={60}>60 минут</option><option value={90}>90 минут</option></select></label></div></section><label className="hint-toggle" htmlFor="include-hints"><input id="include-hints" type="checkbox" {...form.register("includeHints")}/><span><strong>Подсказки во время интервью</strong><small>Идеи для ответа и ориентиры по вопросу</small></span></label></div>{form.formState.errors.root && <p className="setup-error" role="alert">{form.formState.errors.root.message}</p>}<footer className="setup-footer"><p>Настройки можно изменить перед следующим интервью.</p><button disabled={createState.isLoading} type="submit">{createState.isLoading ? "Подготавливаем…" : "Начать репетицию"}<Sparkles/></button></footer></section></form>;
}
function Choice({ active, meta, onClick, title }: { active: boolean; meta: string; onClick: () => void; title: string }) { return <button aria-checked={active} className={active ? "mode-button mode-button--active" : "mode-button"} onClick={onClick} role="radio" type="button"><strong>{title}</strong><small>{meta}</small></button>; }
function Tab({ active, icon, onClick, title }: { active: boolean; icon: React.ReactNode; onClick: () => void; title: string }) { return <button aria-selected={active} className={active ? "source-tab source-tab--active" : "source-tab"} onClick={onClick} role="tab" type="button">{icon}{title}</button>; }
function ErrorText({ error }: { error?: string }) { return error ? <span className="field-error">{error}</span> : null; }
function OptionGroup<T extends string>({ onChange, title, value, values }: { onChange: (value: T) => void; title: string; value: T; values: readonly { value: T; text: string; title?: string }[] }) { return <section className="parameter-group"><h3>{title}</h3><div className="option-cards" role="radiogroup">{values.map((option) => <button aria-checked={value === option.value} className={value === option.value ? "option-card option-card--active" : "option-card"} key={option.value} onClick={() => onChange(option.value)} role="radio" type="button"><strong>{option.title ?? option.text}</strong>{option.title && <small>{option.text}</small>}</button>)}</div></section>; }
function isSameDraft(a: SessionDraft, b: SessionDraft) { return a.vacancy === b.vacancy && a.profile === b.profile && a.format === b.format && a.level === b.level && a.questionsCount === b.questionsCount && a.durationMinutes === b.durationMinutes && a.includeHints === b.includeHints; }
